general.import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]


[window]
padding = { x = 0, y = 10 }
opacity = 0.8
blur = true

[window.dimensions]
columns = 60
lines = 20

[font]
normal.family = "JetBrains Mono"
