[helpers]

[settings]
default_target_type = "symbolic"

[alacritty.files]
"alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"
"alacritty/catppuccin-mocha.toml" = "~/.config/alacritty/catppuccin-mocha.toml"

[fuzzel.files]
"fuzzel/fuzzel.ini" = "~/.config/fuzzel/fuzzel.ini"

[hyfetch.files]
"neofetch/hyfetch.json" = "~/.config/hyfetch.json"
"neofetch/config.jsonc" = "~/.config/fastfetch/config.jsonc"

[wlr-keybinds.files]
"wlr-which-key/config.yaml" = "~/.config/wlr-which-key/config.yaml"

[scripts.files]
"scripts" = {"target" = "~/.config/scripts", "type"="symbolic", "recurse"=false}

[mako.files]
"mako/config" = "~/.config/mako/config"

[sway]
depends = ["sway-waybar", "scripts","mako", "wlogout"]

[sway.files]
"sway/config" = "~/.config/sway/config"
"sway/catppuccin-mocha" = "~/.config/sway/catppuccin-mocha"

[wlogout.files]
"wlogout/layout" = "~/.config/wlogout/layout"

[sway-waybar.files]
"sway/waybar/config.jsonc" = "~/.config/waybar/config.jsonc"
"sway/waybar/style.css" = "~/.config/waybar/style.css"
"sway/waybar/mocha.css" = "~/.config/waybar/mocha.css"

[vesktop.files]
"vesktop/settings.json" = "~/.config/vesktop/settings.json"
"vesktop/settings" = {target = "~/.config/vesktop/settings", type = "symbolic", recurse = false}
"vesktop/themes" = {target = "~/.config/vesktop/themes", type = "symbolic", recurse = false}

[xdg-theming.files]
"gtk-3.0/settings.ini" = "~/.config/gtk-3.0/settings.ini"